# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 06:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('identifier', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=5000)),
                ('target', models.CharField(max_length=50)),
                ('algorithm_names', models.CharField(max_length=1000)),
            ],
        ),
    ]
