# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='max_algorithm_score',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
