# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_model_max_algorithm_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='typeOfData',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='model',
            name='max_algorithm_score',
            field=models.CharField(max_length=100),
        ),
    ]
