# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170802_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='typeOfData',
            field=models.CharField(max_length=100),
        ),
    ]
