# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 13:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170802_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=50)),
                ('runType', models.CharField(max_length=50)),
                ('viewed', models.CharField(max_length=50)),
            ],
        ),
    ]
